ALTER TABLE `criteria_review` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `review_form` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `event_categories` ADD `slug` VARCHAR(100) NOT NULL AFTER `name`;
ALTER TABLE `news` CHANGE `tags` `tags` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `events` ADD `tags` TEXT NULL AFTER `slug`;
ALTER TABLE `events` ADD `status` VARCHAR(50) NOT NULL DEFAULT 'draft' AFTER `short_description`;
ALTER TABLE `events` CHANGE `registration` `free` FLOAT NULL;
ALTER TABLE `events` DROP `short_description`;
ALTER TABLE `events` CHANGE `start_time` `start_time` DATETIME NOT NULL;
ALTER TABLE `events` CHANGE `end_time` `end_time` DATETIME NOT NULL;
ALTER TABLE `events` CHANGE `venue` `venue` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `events` CHANGE `trainer` `trainer` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `events` CHANGE `trainer` `trainer` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `events` ADD `last_updated_by` INT NOT NULL AFTER `status`, ADD `created_by` INT NOT NULL AFTER `last_updated_by`;
ALTER TABLE `events` CHANGE `free` `fee` FLOAT NOT NULL;